name = "Cocoa-EH"
license = "MIT"
licenselink = "https://github.com/fuegowolf/cocoa-eh-hugo-theme/blob/master/LICENSE.md"
description = "A enhanced version of Cocoa. Consistent, responsive theme with clean typography"
homepage = "https://github.com/fuegowolf/cocoa-eh-hugo-theme"
tags = ["open-sans", "minimal", "clean", "ionicons", "comments"]
features = ["blog", "responsive", "404", "icons", "disqus", "metadata"]
min_version = 0.18

[author]
    name = "Alexis Tacnet"
    homepage = "https://github.com/fuegowolf"

[original]
    name = "Nishanth Shanmugham"
    homepage = "https://github.com/nishanths"
    repo = "https://www.github.com/nishanths/cocoa-hugo-theme"
