languageCode: "en-us"
baseurl: "https://netw0rk.io/"
theme: "cocoa-eh-custom"
builddrafts: true
canonifyurls: true
contentdir: "content"
languageCode: "en-US"
layoutdir: "layouts"
publishdir: "public"
author: "sBani"
title: "netw0rk.io"
pluralizelisttitles: false

permalinks:
  blog: "blog/:slug/"

params:
  dateform: "Jan 2, 2006"
  dateformfull: "Mon Jan 2 2006 15:04:05 MST"
  description: "Blog"
  faviconfile: "favicon.ico"
  highlightjs: true
  lang: "en"
  github: "sbani"
  email: "blog@sbani.net"
