# Header
menu:
  Blog: /
  About: /about

# SubNav
subnav:
  github: https://github.com/sbani
  twitter: https://twitter.com/sbani_ger
  rss: /atom.xml

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: UA-3683689-6
favicon: /img/favicon/favicon.ico

avatar: /img/github-avatar.png
share: false
duoshuo: false
tagcloud: false
friends: false
aboutme: false